# -*- coding: utf-8 -*-
"""transformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xlXIuNp8IhNIKy9VZ8y6_mgTpi0E93UK
"""

pip install transformers

from transformers import pipeline

analyzer = pipeline("sentiment-analysis")

text_input = input('enter some text:')

result = analyzer(text_input)

result

text_input = input('enter some text:')

result = analyzer(text_input)

result

generate = pipeline("text-generation")

statement = input('enter any short statement:')

result = generate(statement,max_length=150)

result

entity = pipeline('ner')

text = input('enter a statement:')

result = entity(text)

result

q_a = pipeline('question-answering')

result = q_a({
    'question':'Why does Seraphina enter the Silent Forest?',
    'context':"""
    **The Song of the Silent Forest**
Seraphina, a healer, enters the Silent Forest to find a cure for her dying brother, Callum. The forest is eerie and silent, with no sounds or creatures. After days of wandering, she encounters a massive, ancient tree and a mystical Guardian who offers her the cure—but at a price.

The Guardian tells her that to save her brother, she must sacrifice something important to her. Seraphina agrees to give up her ability to feel joy, believing it’s the only way to save him.

She drinks from a pool at the base of the tree, and immediately, her brother is healed. However, Seraphina feels a deep sadness in her heart as she realizes she has lost her ability to experience happiness.

Returning home, Seraphina finds her brother healthy, but she is forever joyless, having paid a heavy price for his life.
"""

})

result

summarize = pipeline('summarization')

text = input('')

result = summarize(text,max_length=25,min_length=20)

result

while True:
    question = input("Ask a question about Flipkart: ")
    result = q_a({
        'question': question,
        'context': """
        Flipkart is one of India’s largest and most popular e-commerce platforms, offering a vast range of products including electronics, fashion, home appliances, and more. Founded in 2007, Flipkart revolutionized online shopping in India by providing customers with a convenient and reliable way to shop from the comfort of their homes. With its user-friendly app and website, Flipkart provides attractive deals, easy payment options, and fast delivery services, making it a preferred choice for millions of shoppers. Over the years, Flipkart has expanded its services to include features like easy returns, customer reviews, and a secure payment gateway, helping build trust and loyalty among its users. It continues to innovate by incorporating the latest technology to improve user experience and broaden its product offerings.
        """
    })
    print(result)

result

translator = pipeline('translation_en_to_fr')