# -*- coding: utf-8 -*-
"""transformers1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3DP8ZUghSOB_oSAx_xc9nzB657aSRuR
"""

pip install transformers

from transformers import pipeline

translator = pipeline('translation_en_to_de')

text = input('Enter some text: ')

result = translator(text)

result

f_n = pipeline('fill-mask')

text = input('Enter sentence <mask> ')

result = f_n(text)

result

#VISUAL Q_A
vqa_pipeline = pipeline('visual-question-answering')

image=r'/content/peacock.jfif'

question=input('enter a question to ask about image:')
result=vqa_pipeline(image,question)
print (result)

!pip install diffuser

from transformers import pipeline
import torch
from diffusers import DiffusionPipeline

generator=DiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4")
generator.to("cuda")

prompt = 'unicorn flying in the sky image'

image=generator(prompt).images[0]

image

from transformers import pipeline
t_g = pipeline('text-generation')

import time
from matplotlib import pyplot
l = ["he's old and hard working",'child labours','old monk holding to tree']
while True:
  for i in l:
    inp = t_g(i)
    img=generator(inp[0]['generated_text']).images[0]
    pyplot.imshow(img)
    pyplot.show()
    time.sleep(1)

